### ISSUE TITLE
generar orden de alquiler proveedor sugerido

### ISSUE THREAD

**Issue by jaimeforerog** [SincosoftSAS/MYE#10]
generar orden de alquiler por proveedor sugerido, teniendo en cuenta las vigencias en las listas de precios.

**Comment by maicoll31** [comment]
[Ajustes_ProvedorSugerido.docx](https://github.com/SincosoftSAS/MYE/files/14499077/Ajustes_ProvedorSugerido.docx)

**Comment by maicoll31** [comment]
[Ajustes_ProvedorSugerido_Revisión1.docx](https://github.com/SincosoftSAS/MYE/files/14499183/Ajustes_ProvedorSugerido_Revision1.docx)

**Comment by maicoll31** [comment]
[Ajustes_ProvedorSugerido_Revisión1.docx](https://github.com/SincosoftSAS/MYE/files/14515367/Ajustes_ProvedorSugerido_Revision1.docx)
[Ajustes_ProvedorSugerido_Revisión2.docx](https://github.com/SincosoftSAS/MYE/files/14515369/Ajustes_ProvedorSugerido_Revision2.docx)
