### ISSUE TITLE
daños genericos a equipos de alquiler

### ISSUE THREAD

**Issue by jaimeforerog** [SincosoftSAS/MYE#11]
daños genericos a equipos de alquiler

**Comment by maicoll31** [comment]
Documentos de revisión
[REVISIÓN_DAÑOS_GENERICOS_1.docx](https://github.com/SincosoftSAS/MYE/files/14669507/REVISION_DANOS_GENERICOS_1.docx)
[REVISIÓN_DAÑOS_GENERICOS_2.docx](https://github.com/SincosoftSAS/MYE/files/14669509/REVISION_DANOS_GENERICOS_2.docx)


Instructivo
[INSTRUCTIVO DAÑOS GENÉRICOS.docx](https://github.com/SincosoftSAS/MYE/files/14379458/INSTRUCTIVO.DANOS.GENERICOS.docx)

Power automate
Sincosoft SAS\2024 - MAQUINARIA Y EQUIPOS 2024\M&E\Automatizaciones\ALQUILER\Daños_Genericos
