### ISSUE TITLE
Agregar adjuntos a variables adicionales y modificar el informe de documentos, listado equipos y app movil.

### ISSUE THREAD

**Issue by Sacast** [SincosoftSAS/MYE#14]
En listado de equipos dentro de la columna de cada variable adicional mostrar el icono para descargar el adjunto.

**Comment by maicoll31** [comment]
Documentos de revición
[DESARROLLO ADJUNTOS EN VARIABLES ADICIONALES_revision2.docx](https://github.com/SincosoftSAS/MYE/files/14541055/DESARROLLO.ADJUNTOS.EN.VARIABLES.ADICIONALES_revision2.docx)
[DESARROLLO ADJUNTOS EN VARIABLES ADICIONALES_revision1.docx](https://github.com/SincosoftSAS/MYE/files/14529539/DESARROLLO.ADJUNTOS.EN.VARIABLES.ADICIONALES_revision1.docx)

Instructivo
[VARIABLES ADICIONALES.docx](https://github.com/SincosoftSAS/MYE/files/14543612/VARIABLES.ADICIONALES.docx)

Power Automate
Sincosoft SAS\2024 - MAQUINARIA Y EQUIPOS 2024\M&E\Automatizaciones\MAQUINARIA/Variables_Adicionales
